/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package airline_server;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aaditya
 */
public class flight_info extends javax.swing.JPanel {

    /**
     * Creates new form for_delete
     */
    public flight_info() {
        initComponents();
        setSize(700,120);
    }

    public void setflightdetails(String code, String name,String source,String destination,String date1,String departure, String arrival,String seat,String func){
        airline_name.setText(name);
        airline_code.setText(code);
        sc.setText(source);
        dest.setText(destination);
        date.setText(date1);
        dep.setText(departure);
        arr.setText(arrival);
        seats.setText(seat);
        if(func.equals("Delete"))
            button.setText("Delete Flight");
        else if(func.equals("View"))
            button.setText("View");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airline_name = new javax.swing.JLabel();
        airline_code = new javax.swing.JLabel();
        sc = new javax.swing.JLabel();
        dest = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        arr = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        button = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        airline_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        airline_name.setText("name");

        airline_code.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        airline_code.setText("code");

        sc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sc.setText("source");

        dest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dest.setText("dest");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("To");

        dep.setText("dep");

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setText("date");

        arr.setText("arr");

        jLabel2.setText("Departure");

        jLabel3.setText("Arrival");

        seats.setText("seat");

        jLabel5.setText("Seats Available");

        button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button.setText("Delete Flight");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(airline_code, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(airline_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(button)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airline_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dest, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airline_code, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dep)
                            .addComponent(arr)
                            .addComponent(seats)))
                    .addComponent(button))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        try(Connection con = Database.connect()){
            if(button.getText().equals("Delete Flight")){
                String q = "DELETE FROM booking WHERE flight_code=?";
                PreparedStatement ps = con.prepareStatement(q);
                ps.setString(1,airline_code.getText());
                ps.executeUpdate();
                
                
                String query = "DELETE FROM flight WHERE flight_code=?";
                 ps = con.prepareStatement(query);
                ps.setString(1,airline_code.getText());
                if(ps.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null,"Flight deleted succesfully!");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Failed to delete flight.");
                }
            }
            else if(button.getText().equals("View")){
                view_info view = new view_info();
                view.get_details(airline_code.getText(),airline_name.getText(),sc.getText(),dest.getText(),dep.getText(),arr.getText(),date.getText());
                view.setVisible(true);
                
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airline_code;
    private javax.swing.JLabel airline_name;
    private javax.swing.JLabel arr;
    private javax.swing.JButton button;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dep;
    private javax.swing.JLabel dest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel sc;
    private javax.swing.JLabel seats;
    // End of variables declaration//GEN-END:variables
}
